# Nice git
Import-Module posh-git
oh-my-posh init pwsh --config  $PSScriptRoot/.oh-my-posh.ostemar.json | Invoke-Expression
Import-Module Terminal-Icons

# Help git with unicode characters
$env:LC_ALL='C.UTF-8'

# Colorize file listings
# Import-Module Get-ChildItemColor
# Set-Alias l Get-ChildItemColorFormatWide -Option AllScope
if (Test-Path Alias:ls) {
    Remove-Item Alias:ls -Force
}
function ls { eza --color=auto --icons=auto --group-directories-first @args }
function la { eza --color=auto --icons=auto --group-directories-first --all --git @args }
function ll { eza --color=auto --icons=auto --group-directories-first --all --git --long @args }
function l { eza --color=auto --icons=auto --group-directories-first --all --git --long @args }

# sql alias
Set-Alias sql Invoke-SqlCmd

# ~ as home
function cuserprofile { Set-Location ~ }
Set-Alias ~ cuserprofile -Option AllScope

# Short cheat codes because I am lazy
Set-Alias vi nvim -Option AllScope
Set-Alias vim nvim -Option AllScope
Set-Alias v nvim -Option AllScope
Set-Alias lg lazygit -Option AllScope

# Key bindings
Set-PSReadlineKeyHandler -Chord Ctrl+d -Function DeleteCharOrExit
Set-PSReadlineKeyHandler -Chord Ctrl+a -Function BeginningOfLine
Set-PSReadlineKeyHandler -Chord Ctrl+e -Function EndOfLine

# Helper function to show Unicode character
function U
{
    param
    (
        [int] $Code
    )

    if ((0 -le $Code) -and ($Code -le 0xFFFF))
    {
        return [char] $Code
    }

    if ((0x10000 -le $Code) -and ($Code -le 0x10FFFF))
    {
        return [char]::ConvertFromUtf32($Code)
    }

    throw "Invalid character code $Code"
}

# OSR CLI Tool - Auto-generated by 'osr init'
function osr {
    $originalLocation = Get-Location
    try {
        # Find git repository root
        $gitRoot = $null
        $currentPath = Get-Location
        
        while ($currentPath) {
            if (Test-Path (Join-Path $currentPath ".git")) {
                $gitRoot = $currentPath
                break
            }
            $parent = Split-Path -Parent $currentPath
            if ($parent -eq $currentPath) {
                break
            }
            $currentPath = $parent
        }
        
        if (-not $gitRoot) {
            Write-Host "Error: Not inside a git repository" -ForegroundColor Red
            return
        }
        
        # Navigate to repository root and execute osr.ps1
        Push-Location $gitRoot
        $osrScript = Join-Path $gitRoot "osr.ps1"
        
        if (-not (Test-Path $osrScript)) {
            Write-Host "Error: osr.ps1 not found in repository root: $gitRoot" -ForegroundColor Red
            return
        }
        
        # Check if this is a "goto" command - handle it specially
        if ($args.Count -ge 2 -and $args[1] -match '^(goto|g)$') {
            # Set environment variable to signal goto mode
            $env:OSR_GOTO_MODE = "1"
            $targetPath = & pwsh -NoProfile -File $osrScript @args
            $env:OSR_GOTO_MODE = $null
            
            # Change to the target directory in the current shell
            if ($targetPath -and (Test-Path $targetPath)) {
                Pop-Location
                Set-Location $targetPath
                Write-Host "Changed directory to: $targetPath" -ForegroundColor Green
                return
            }
        }
        
        # Normal command execution
        & pwsh -NoProfile -File $osrScript @args
    }
    finally {
        Pop-Location
    }
}